### ISSUE TITLE
ed25519-sha512はもうed25519でいいかも

### ISSUE THREAD

**Issue by mei23** [misskey-dev/node-http-message-signatures#2]
https://github.com/misskey-dev/node-http-message-signatures/blob/1598c72b8ebd6c14036216379e02ebe5647d794c/src/utils.ts#L49

**Comment by tamaina** [comment]
ed25519-sha512で認識しない実装がないならこのままでいい気もする

**Comment by tamaina** [comment]
（どうせドラフト実装なので旧実装との互換性重視で行きたい

**Comment by mei23** [comment]
まあ、**ドラフトには**`ed25519`ないから仕方ないか

将来的にRFCで送るなら`ed25519`だわね
