### ISSUE TITLE
Web Crypto APIを使う

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/node-http-message-signatures#3]
汎用性が増す

（Nodeでのパフォーマンス面での違いがなければ実装したい）

**Comment by mei23** [comment]
普通に出来そうだけどEd25519がExperimentalなのが気になるわね
https://nodejs.org/api/webcrypto.html#ed25519ed448x25519x448-key-pairs

**Comment by tamaina** [comment]
crypto.subtle.importKey、なんかalgorithmを提供する必要があるらしく面倒

https://developer.mozilla.org/ja/docs/Web/API/SubtleCrypto/importKey#algorithm

spkiにアルゴリズム情報があるんだからパースしてくれ

(しかもRSA鍵はハッシュアルゴリズムを事前指定させるのどういうことなんだ)

**Comment by tamaina** [comment]
![image](https://github.com/misskey-dev/node-http-message-signatures/assets/7973572/6bd84e1b-2976-473a-a0e0-26be8e213c56)

なんかWeb Crypto APIの方が署名検証早いんすけど

**Comment by tamaina** [comment]
`@lapo/asn1js`がesbuildでうまくバンドルできない

**Comment by tamaina** [comment]
https://github.com/misskey-dev/node-http-message-signatures/blob/0b2ef2318aca1b405f92d1ae2da10e0a8ecd2b24/src/keypair.ts#L79-L87 (PKCS1→SPKI)とか https://github.com/misskey-dev/node-http-message-signatures/blob/0b2ef2318aca1b405f92d1ae2da10e0a8ecd2b24/src/utils.ts#L10 (PKCS8のパース)とかも自前で実装する必要があるのか

**Comment by tamaina** [comment]
ところで: toSpkiPublicKeyをどっかに突っ込み忘れてるわね？

（多分MisskeyのPersonのKeyレンダリングで補正しているのがそのままやってきたっぽい？）

**Comment by tamaina** [comment]
メモ https://github.com/nodejs/node/blob/7e05126fcab705babefae81bb83c3d310646e5a2/src/crypto/crypto_keys.cc#L1209

**Comment by tamaina** [comment]
> メモ https://github.com/nodejs/node/blob/9930f114a00d17a0b2d6c7f6086aa77c0b971e28/src/crypto/crypto_keys.cc#L104

nodeもやっぱり「SPKIっぽくなかったらPKCS#1にする」という方法をとっていることがわかった

**Comment by tamaina** [comment]
> なんかWeb Crypto APIの方が署名検証早いんすけど

awaitしてなかったんだからそりゃ速いよ…

最新版（Signを実装

![image](https://github.com/misskey-dev/node-http-message-signatures/assets/7973572/572ab395-7152-47f5-ad62-bbf1b2204187)

**Comment by tamaina** [comment]
Web Verifyは改善の余地がありそう

**Comment by tamaina** [comment]
![image](https://github.com/misskey-dev/node-http-message-signatures/assets/7973572/71d30234-866f-4369-aa7b-385c10a35c3d)

Promise.allで処理させたら爆速になった

**Comment by tamaina** [comment]
(node用の実装も残しておきたさはあるけど、Web環境に取り込んでも大丈夫なようにするには工夫が必要そう

**Comment by tamaina** [comment]
うんいらんな

**Comment by tamaina** [comment]
https://github.com/misskey-dev/node-http-message-signatures/commit/8286028414a5f801dea2d515f2d0f3735f2e378a

DraftはWeb Crypto APIで動くようになった

**Comment by tamaina** [comment]
Complete
