### ISSUE TITLE
Node v18で動かない

### ISSUE THREAD

**Issue by mei23** [misskey-dev/node-http-message-signatures#5]
https://github.com/misskey-dev/node-http-message-signatures/actions/runs/8135671039/job/22230611896#step:7:28
```
TypeError: Cannot read properties of undefined (reading 'subtle')
```

v18はglobalに`crypto`がない

**Comment by mei23** [comment]
v18でglobalに出すフラグ
https://nodejs.org/docs/latest-v18.x/api/cli.html#--experimental-global-webcrypto

**Comment by mei23** [comment]
Node v18 メンテナンスフェーズだからまあいいかしら
どうしてもなら https://nodejs.org/docs/latest-v18.x/api/cli.html#--experimental-global-webcrypto フラグで動くと思うので

でも、動作環境はクリアにする必要ありそうだわね。

**Comment by tamaina** [comment]
v20からで良くない？と思っている

（もちろん対応できればそれに越したことはない

**Comment by mei23** [comment]
> v20からで良くない？と思っている

まあ、それでもいいかなとは思ってるわ。
でもこれで動きはすると思うわ。
https://github.com/misskey-dev/node-http-message-signatures/pull/6
